### ISSUE TITLE
Build instruction in package.json isn't working

### ISSUE THREAD

**Issue by shankscoder** [mauro-codes/chrome-extension-with-svelte#1]
Just tried to use the instructions as is, and I got a build error when running `npm run build`

Modified `package.json` as follows and it works:

```
{
...
"scripts":{
    "build": "cpx 'public/**' 'public/**' -C && rollup -c && cpx 'extension/**/*.*' public",
...
}
```

You need to move the options after the source and destination paths for the `cpx` command + you need to escape any patterns in quotes.

**Comment by mauro-codes** [comment]
Thanks, Ashwin! I'll apply your fix! Just curious about if you're using Linux or Mac. I tested this on Windows, and it was working.

Thanks again for taking the time and report it!
